// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpT0dkla3r5WPM_NevC7meQmyK1CnCpc4',
    appId: '1:715692837129:web:a5de153d93daec73ef2bd8',
    messagingSenderId: '715692837129',
    projectId: 'passaporte-ciclorota',
    authDomain: 'passaporte-ciclorota.firebaseapp.com',
    storageBucket: 'passaporte-ciclorota.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh00z3Ze--u0GMXBbFiCONxPs-TJMbjNQ',
    appId: '1:715692837129:android:bda385f4c0dba86eef2bd8',
    messagingSenderId: '715692837129',
    projectId: 'passaporte-ciclorota',
    storageBucket: 'passaporte-ciclorota.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOM4DFjEJQEUBtQSQsgzSEIcO8b3H344A',
    appId: '1:715692837129:ios:5afb2f03e9cc731aef2bd8',
    messagingSenderId: '715692837129',
    projectId: 'passaporte-ciclorota',
    storageBucket: 'passaporte-ciclorota.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOM4DFjEJQEUBtQSQsgzSEIcO8b3H344A',
    appId: '1:715692837129:ios:5afb2f03e9cc731aef2bd8',
    messagingSenderId: '715692837129',
    projectId: 'passaporte-ciclorota',
    storageBucket: 'passaporte-ciclorota.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpT0dkla3r5WPM_NevC7meQmyK1CnCpc4',
    appId: '1:715692837129:web:dacdda90836ab44bef2bd8',
    messagingSenderId: '715692837129',
    projectId: 'passaporte-ciclorota',
    authDomain: 'passaporte-ciclorota.firebaseapp.com',
    storageBucket: 'passaporte-ciclorota.firebasestorage.app',
  );
}
